[package]
name = "rcu_cell"
version = "0.1.8"
description = "a lockless rcu cell implementation"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
categories = ["concurrency", "data-structures"]
keywords = ["rcu", "lockless", "atomic"]
repository = "https://github.com/Xudong-Huang/rcu_cell"
homepage = "https://github.com/Xudong-Huang/rcu_cell"
documentation = "https://docs.rs/rcu_cell"
license = "LGPL-3.0"
readme = "./README.md"
exclude = [
    ".gitignore",
    ".travis.yml",
    "appveyor.yml",
    "benches/**/*",
    "docs/**/*",
]

[badges]
travis-ci = { repository = "Xudong-Huang/rcu_cell" }
